# Generated by Django 2.2.7 on 2020-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('panding', 'panding'), ('apsept', 'apsept'), ('reject', 'reject'), ('reject', 'reject')], max_length=200),
        ),
    ]
