# Generated by Django 2.2.7 on 2020-11-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201105_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
    ]
